# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 01:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('karma', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name=datetime.datetime(2017, 8, 21, 1, 36, 36, 434339, tzinfo=utc))),
                ('karma', models.IntegerField(default=0)),
                ('text', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Subblueit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True)),
                ('followers', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RedditApp.Subblueit'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RedditApp.Post'),
        ),
    ]
