# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 17:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('RedditApp', '0003_auto_20170820_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='RedditApp.Comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 9, 1, 17, 46, 14, 63137, tzinfo=utc)),
        ),
    ]
