# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 19:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('RedditApp', '0007_auto_20170909_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subblueit',
            name='creator',
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 9, 9, 19, 48, 25, 101639, tzinfo=utc)),
        ),
    ]
