# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 21:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('RedditApp', '0008_auto_20170909_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 9, 9, 21, 44, 3, 201186, tzinfo=utc)),
        ),
    ]
